import { injectJsError } from "./lib/jsError";
import { injectXHR } from "./lib/xhr";
import { blankScreen } from "./lib/blankScreen";
import { paint } from "./lib/paint";
import { timing } from "./lib/timing";
injectJsError();
injectXHR();
blankScreen();
timing();
paint();
